from karel.stanfordkarel import *

def main():
    mario()
    take_position()
    luigi()
    take_position
    
def mario():
    move_steps(3)
    move_color(4,BLACK)
    move_steps(4)
    move_color(4,BLACK)
    left_go_up()
    move_color(3,BLACK)
    move_steps(4)
    move_color(3,BLACK)
    right_go_up()
    move_color(3,BLUE)
    move_steps(2)
    move_color(3,BLUE)
    left_go_up()
    move_color(8,BLUE)
    move_color(2,YELLOW)
    turn_around()
    move_steps(9)
    move_color(2,YELLOW)
    left_go_up()
    paint_corner(YELLOW)
    move_color(2,YELLOW)
    move_color(6,BLUE)
    move_color(3,YELLOW)
    right_go_up()
    paint_corner(YELLOW)
    move_color(1,YELLOW)
    move_color(1,RED)
    move_color(1,BLUE)
    move_color(1,YELLOW)
    move_color(2,BLUE)
    move_color(1,YELLOW)
    move_color(1,BLUE)
    move_color(1,RED)
    move_color(2,YELLOW)
    left_go_up()
    paint_corner(RED)
    move_color(3,RED)
    move_color(4,BLUE)
    move_color(4,RED)
    right_go_up()
    move_color(3,RED)
    move_color(1,BLUE)
    move_color(2,RED)
    move_color(1,BLUE)
    move_color(3,RED)
    left_go_up()
    move_color(2,RED)
    move_color(1,BLUE)
    move_color(2,RED)
    move_color(1,BLUE)
    move_color(2,RED)
    right_go_up()
    move_color(6,YELLOW)
    move_steps(3)
    left_go_up()
    move_color(4,BLACK)
    move_color(4,YELLOW)
    move_color(1,BLACK)
    move_steps(2)
    right_go_up()
    move_color(1,BLACK)
    move_color(1,YELLOW)
    move_color(2,BLACK)
    move_color(3,YELLOW)
    move_color(1,BLACK)
    move_color(3,YELLOW)
    left_go_up()
    move_color(3,YELLOW)
    move_color(1,BLACK)
    move_color(3,YELLOW)
    move_color(1,BLACK)
    move_color(1,YELLOW)
    move_color(1,BLACK)
    right_go_up()
    move_color(3,BLACK)
    move_color(2,YELLOW)
    move_color(1,BLACK)
    move_color(1,YELLOW)
    move_steps(3)
    left_go_up()
    move_color(9,RED)
    right_go_up()
    move_color(5,RED)
    
    
def take_position():
    move_steps(5)
    turn_right()
    move_steps(15)
    turn_left()
    move_steps(4)
    if front_is_clear():
        move()

def luigi():
     move_steps(3)
     move_color(4,BLACK)
     move_steps(4)
     move_color(4,BLACK)
     left_go_up()
     move_color(3,BLACK)
     move_steps(4)
     move_color(3,BLACK)
     right_go_up()
     move_color(3,BLUE)
     move_steps(2)
     move_color(3,BLUE)
     left_go_up()
     move_color(8,BLUE)
     move_color(2,YELLOW)
     turn_around()
     move_steps(9)
     move_color(2,YELLOW)
     left_go_up()
     paint_corner(YELLOW)
     move_color(2,YELLOW)
     move_color(6,BLUE)
     move_color(3,YELLOW)
     right_go_up()
     paint_corner(YELLOW)
     move_color(1,YELLOW)
     move_color(1,RED)
     move_color(1,BLUE)
     move_color(1,YELLOW)
     move_color(2,BLUE)
     move_color(1,YELLOW)
     move_color(1,BLUE)
     move_color(1,RED)
     move_color(2,YELLOW)
     left_go_up()
     paint_corner(GREEN)
     move_color(3,GREEN)
     move_color(4,BLUE)
     move_color(4,GREEN)
     right_go_up()
     move_color(3,GREEN)
     move_color(1,BLUE)
     move_color(2,GREEN)
     move_color(1,BLUE)
     move_color(3,GREEN)
     left_go_up()
     move_color(2,GREEN)
     move_color(1,BLUE)
     move_color(2,GREEN)
     move_color(1,BLUE)
     move_color(2,GREEN)
     right_go_up()
     move_color(6,YELLOW)
     move_steps(2)
     left_go_up()
     move_color(1,BLACK)
     move_color(4,YELLOW)
     move_color(4,BLACK)
     move_steps(2)
     right_go_up()
     move_color(3,YELLOW)
     move_color(1,BLACK)
     move_color(3,YELLOW)
     move_color(2,BLACK)
     move_color(1,YELLOW)
     move_color(1,BLACK)
     left_go_up()
     paint_corner(BLACK)
     move_color(1,YELLOW)
     move_color(1,BLACK)
     move_color(3,YELLOW)
     move_color(1,BLACK)
     move_color(3,YELLOW)
     right_go_up()
     move()
     move_color(1,YELLOW)
     move_color(1,BLACK)
     move_color(2,YELLOW)
     move_color(3,BLACK)
     left_go_up()
     paint_corner(GREEN)
     move_color(8,GREEN)
     right_go_up()
     move_steps(2)
     move_color(5,GREEN)
    
    
    

def move_steps(steps):
    for i in range(steps):
        move()

def move_color(steps,color):
    for i in range(steps):
        move()
        paint_corner(color)

def left_go_up():
    turn_left()
    move()
    turn_left()

def right_go_up():
    turn_right()
    move()
    turn_right()


def turn_right():
    for i in range(3):
        turn_left()

def turn_around():
    for i in range(2):
        turn_left()
        

if __name__=="__main__":
    run_karel_program("40x20.w")
