g_name=["AATHITHEYA  A.","AFRIN JUMANA M.","BHAVANIDEVI  B.G.","CHALENE  T.","DEEPTHI  J.H.","DHURGA  S.","HARITHA SRI  S.","INDHUMATHI  K.V.","JEEVA GETZIE CYNTHIA  A.","JEROLIN FUTINA  J.B.","JOYLINE CHRISTY  J.","KANAKADURGA  J.M.","KAVIYA PRABHA  M.P.","KEERTHANA  R.","MAHA PRIYA  T.","NANDHINI  P.","NARMADHA  A.D.","PANDIA ABINAYA P.","POORNA SHIVANI G.","PRIYA M.","PRIYANKA  N.J.","SAI SWAROOPA  S.S.","SAKTHI KANIPRIYA  S.","SAKTHI MALAVIKA  U.","SANGAVI  S.","SANJU VIGASINI  K.S.","SHANMUGA PRIYA R.","SHIYAMALA K.","SOUNDARYA  G.","SRINITHI  A.","SUBA SRI  R.","YAZHINI  S.","YOGAPANDEESWARI  S.","ABISHEK RAM  G.","ABU BACKER SIDDIQ  B.","ARAVINTH  P.","ARUN  G.V.","ARUN SUNDAR  K.","EDWIN ANTHONY L.","GOKUL SHYAM M.","HARIPRAKASH  S.","JABEL GADSON  G.","JAYAVEERA PANDIAN  S.","JEYRENGARAJENDIRAN  J.","MANTRAES P.V.S.","MAYA JEGADISH  P.","MOHAMMED ABDUL QAYYUM  M.","MOHITH VEERESHWAR  K.","MUTHALAGU S.","NAVEEN BABU  S.","RAGHU RAMAN  S.","RAMVIGNESH  R.","SANTHOSH  M.G.","SARAVANAN  M.","SIVAMANIBALA S.","SRIVARTSHAN  M.","SUDHARSAN  R.","SUGESH  G.","VIGNESH  K.","ZEKKIN THANRAJ  S."];
t=true;
c=string(c);
while t
    a=string(g_name(randi([1,length(g_name)],1,1)));
    if ~(any(c==a))
        t=false;
    end
end
c=[c,a];
a
